### PR TITLE
Correct numeric type for lifetimes on TenantSettings

### LINKED ISSUE #271: Typing mismatch in TenantSettingsBase IdleSessionLifetime and SessionLifetime properties
### Description

The TenantSettingsBase class stores IdleSessionLifetime and Sessionlifetime as nullable ints -- and these values are set in minutes in the management site. When calling TenantSettings.GetAsync(), the values are returned as hours, and as a result I am receiving 0.25 for IdleSessionLifetime when the IdleSessionLifetime is set to 15 minutes. Naturally attempting to deserialize a floating-point number into an int throws an exception:

`Unhandled Exception: Newtonsoft.Json.JsonReaderException: Input string '0.25' is not a valid integer. Path 'idle_session_lifetime', line 1, position 562.`

If the intended behavior is indeed for the Auth0 management APIs to represent the session lifetime fields in hours, then the TenantSettingsBase class should be updated to store these fields as decimals rather than ints. 

### Environment

Please provide the following:

- Version of Auth0.NET used: 6.3.0
- Version of .NET used: .NET Standard 2.0

### Reproduction
Query the TenantSettings of a tenant with an SessionLifetime/IdleSessionLifetime not divisible by 60.
[stack_trace.txt](https://github.com/auth0/auth0.net/files/3408634/stack_trace.txt)

### PR DESCRIPTION
**Pull request by damieng**
This corrects the type of SessionLifetime and IdleSessionLifetime on the TenantSettings(Base) class.

Fixes #271

### CODE REVIEW

File: src/Auth0.ManagementApi/Models/TenantSettingsBase.cs [hunk 1]
```diff
@@ -83,13 +83,13 @@ public class TenantSettingsBase
         /// Login session lifetime, how long the session will stay valid (unit: hours).
         /// </summary>
         [JsonProperty("session_lifetime")]
-        public int? SessionLifetime { get; set; }
+        public float? SessionLifetime { get; set; }
```
Comment (rcollipi) [inline src/Auth0.ManagementApi/Models/TenantSettingsBase.cs]: Would it be an issue to represent these as decimal values rather than as floats?

File: src/Auth0.ManagementApi/Models/TenantSettingsBase.cs [hunk 2]
```diff
@@ -83,13 +83,13 @@ public class TenantSettingsBase
...
 
         /// <summary>
         /// Force a user to login after they have been inactive for the specified number (unit: hours).
         /// </summary>
         [JsonProperty("idle_session_lifetime")]
-        public int? IdleSessionLifetime { get; set; }
+        public float? IdleSessionLifetime { get; set; }
```
Comment (rcollipi) [inline src/Auth0.ManagementApi/Models/TenantSettingsBase.cs]: Would it be an issue to represent these as decimal values rather than as floats?

File: src/Auth0.ManagementApi/Models/TenantSettingsBase.cs (hunk 1 above)
Comment (damieng) [reply src/Auth0.ManagementApi/Models/TenantSettingsBase.cs]: They are IEEE 754 floats on the server side (JavaScript) so you'll only get values that can be contained in floats in .NET too.  There would be no extra precision gained using a Decimal.

File: src/Auth0.ManagementApi/Models/TenantSettingsBase.cs (hunk 2 above)
Comment (damieng) [reply src/Auth0.ManagementApi/Models/TenantSettingsBase.cs]: Same response.

File: src/Auth0.ManagementApi/Models/TenantSettingsBase.cs (hunk 1 above)
Comment (rcollipi) [reply src/Auth0.ManagementApi/Models/TenantSettingsBase.cs]: Seems reasonable to me!
